import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BuildMentor Academy",
  description: "BuildMentor Academy is a comprehensive online learning platform designed to empower construction project managers with the skills, knowledge, and mentorship they need to excel in their roles. From foundational principles to advanced strategies, our courses cover all aspects of construction management, providing practical insights and real-world solutions. Whether you're a seasoned professional or just starting out in the industry, BuildMentor Academy is your trusted partner in achieving construction project mastery. Generated by create next app.",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
